sudo: true

language: node_js

node_js:
    - 10

cache:
    directories:
        - node_modules

before_install:
    - npm i -g github-release-from-changelog

deploy:
    - provider: script
      github_token: $GITHUB_TOKEN
      script: github-release-from-changelog
      skip_cleanup: true
      on:
          tags: true
