name: "Release Vscode Plugin"
on:
  push:
    tags:
      - v*
jobs:
  npmInstall:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: npm install -g vsce
      - run: yarn install
      - run: yarn lint
      - run: yarn compile
      - run: vsce publish -p ${{ secrets.PUBLISHER_TOKEN }}
