name: "Release Vscode Plugin"
on:
  push:
    branches:
      - master
    tags:
      - v*
jobs:
  npmInstall:
    name: npm install
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn install
      - run: yarn lint
      - run: yarn compile
    name: Release plugin
    steps:
      - uses: JCofman/vscodeaction@master
        env:
          PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}
        with:
          args: publish -p $PUBLISHER_TOKEN
