name: "Release Vscode Plugin"
on:
  push:
    tags:
      - v*
env:
  GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
  PUBLISHER_TOKEN: ${{ secrets.PUBLISHER_TOKEN }}

jobs:
  npmInstall:
    name: Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn
      - run: yarn lint
      - run: yarn compile
      - run: npx github-release-from-changelog

  vscPublish:
    name: Release Extension
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: "10.x"
      - run: yarn
      - run: npx vsce publish
